// <auto-generated />
namespace PatternsKurs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _0004 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0004));
        
        string IMigrationMetadata.Id
        {
            get { return "202001081246335_0004"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
