// <auto-generated />
namespace PatternsKurs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _0007 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0007));
        
        string IMigrationMetadata.Id
        {
            get { return "202001121405162_0007"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
